{
 "title": "Hello World Performance Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Environment", "query": "example-namespace-name" }
  ]
 },
 "panels": [
  {
   "title": "% of CPU Limit Used by Containers (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"}[5m])) by (namespace,container) / sum(kube_pod_container_resource_limits{resource=\"cpu\",namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"}) by (namespace,container) ) * 100",
     "legendFormat": "{container:{{container}}, pod:{{pod}}, namespace:{{namespace}} }"
    }
   ]
  },
  {
   "title": "% of Memory Limit Used by Containers (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(container_memory_max_usage_bytes{namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"}) by (namespace,container) / sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"}) by (namespace,container))*100",
     "legendFormat": "{container:{{container}}, pod:{{pod}}, namespace:{{namespace}} }"
    }
   ]
  },
  {
   "title": "% of File System Limit Used by Container (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(container_fs_usage_bytes{namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"} / container_fs_limit_bytes{namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"})*100",
     "legendFormat": "{container:{{container}}, pod:{{pod}}, namespace:{{namespace}} }"
    }
   ]
  },
  {
   "title": "File System Reads by Container (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"}",
     "legendFormat": "{container:{{container}}, pod:{{pod}}, namespace:{{namespace}} }"
    }
   ]
  },
  {
   "title": "File System Writes by Container (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{namespace=~\"${Namespace}\",container!=\"POD\",container!=\"istio-proxy\"}[5m])",
     "legendFormat": "{container:{{container}}, pod:{{pod}}, namespace:{{namespace}} }"
    }
   ]
  },
  {
   "title": "Container Network Bytes Received (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=~\"${Namespace}\"}[5m])",
     "legendFormat": "{container:{{container}}, pod:{{pod}}, namespace:{{namespace}} }"
    }
   ]
  },
  {
   "title": "Container Network Bytes Transmitted (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=~\"${Namespace}\"}[5m])",
     "legendFormat": "{container:{{container}}, pod:{{pod}}, namespace:{{namespace}} }"
    }
   ]
  }
 ]
}